/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 8b83d6e1a5058a8fbae13fa7761b483c)
interface __BaseEnv_Env {
	mary_sens_db: D1Database;
	ASSETS: Fetcher;
	NEXT_PUBLIC_SUPABASE_URL: string;
	NEXT_PUBLIC_SUPABASE_ANON_KEY: string;
	SUPABASE_SERVICE_ROLE_KEY: string;
	NEXT_PUBLIC_WHATSAPP_NUMBER: string;
	ADMIN_GATE_PATH: string;
	ADMIN_GATE_SECRET: string;
	BETTER_AUTH_SECRET: string;
	BETTER_AUTH_URL: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
