/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 31d0fd35dde646350d28b8775b7e2488)
interface __BaseEnv_Env {
	DB: D1Database;
	ASSETS: Fetcher;
	NEXT_PUBLIC_SUPABASE_URL: string;
	NEXT_PUBLIC_SUPABASE_ANON_KEY: string;
	SUPABASE_SERVICE_ROLE_KEY: string;
	NEXT_PUBLIC_WHATSAPP_NUMBER: string;
	ADMIN_GATE_PATH: string;
	ADMIN_GATE_SECRET: string;
	BETTER_AUTH_SECRET: string;
	BETTER_AUTH_URL: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.open-next/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
