/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 81d1b45b132e2138f3b699335bcad36f)
interface __BaseEnv_Env {
	DB: D1Database;
	ASSETS: Fetcher;
	BETTER_AUTH_SECRET: string;
	BETTER_AUTH_URL: string;
	CLOUDINARY_CLOUD_NAME: string;
	CLOUDINARY_API_KEY: string;
	CLOUDINARY_API_SECRET: string;
	ADMIN_GATE_PATH: string;
	ADMIN_GATE_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.open-next/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
